// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PowerSuggestion
{
    internal sealed partial class Vsix
    {
        public const string Id = "PowerSuggestion.32701f3f-79cd-4a5b-9599-3168b136d60d";
        public const string Name = "PowerSuggestions";
        public const string Description = @"Power Suggestions is a CRM Tool Extension for Visual Studio that Provides with Entity Name and Entity Field Suggestions for user. From now on don't keep power apps aside to see entity logical name or entity field type.";
        public const string Language = "en-US";
        public const string Version = "1.1";
        public const string Author = "Bhavya Joshi";
        public const string Tags = "";
    }
}
