// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace PowerSuggestion
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string PowerSuggestionString = "f1e4e6b5-6ce4-4407-8f6a-0605a07ce473";
        public static Guid PowerSuggestion = new Guid(PowerSuggestionString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int CRMMenu = 0x0001;
        public const int ConnectCRM = 0x0100;
        public const int OpenSuggestionWindow = 0x0101;
    }
}